# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20160524_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
