# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 10:05
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Permission, Group


def add_groups(apps, schema_editor):
    teachers, created_teachers = Group.objects.get_or_create(name='teachers')
    students, created_students = Group.objects.get_or_create(name='students')

    can_add_booking = Permission.objects.get(name='Can add booking')
    can_delete_booking = Permission.objects.get(name='Can delete booking')
    can_change_booking = Permission.objects.get(name='Can change booking')

    teachers.permissions.add(
        can_add_booking,
        can_delete_booking,
        can_change_booking,
    )

    teachers.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_groups)
    ]
